# Sample workflow for building and deploying a Jekyll site to GitHub Pages
name: Deploy Jekyll site to Pages

on:
  # Runs on pushes targeting the default branch
  push:
    branches: ["master"]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: read
  pages: write
  id-token: write

# Allow one concurrent deployment
concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  changes:
    runs-on: ubuntu-latest
    outputs:
      subfolder: ${{ steps.changes.outputs.subfolder }}
      rootfolder: ${{ steps.changes.outputs.rootfolder }}
    steps:
    - uses: actions/checkout@v3
    - uses: dorny/paths-filter@v2
      id: changes
      with:
        filters: |
          subfolder:
            - 'md-files/**'
          rootfolder:
            - '*.*'
            - '!md-files/**'

  #Build jobs
  build_sapl_reference:
    name: Build SAPL-Reference
    needs: changes
    if: ${{ needs.changes.outputs.subfolder == 'true' }}
    permissions:
      contents: write
      pages: write
      id-token: write
      pull-requests: write
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
#        with:
#          sparse-checkout: md-files/saplReference
  
      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.3' # Not needed with a .ruby-version file
          bundler-cache: true # runs 'bundle install' and caches installed gems automatically
          cache-version: 1 # Increment this number if you need to re-download cached gems
      - name: Setup Pages
        id: pages
        uses: actions/configure-pages@v3
      - run:  |
          gem install bundler
          bundle install
          bundle exec jekyll build
        working-directory: ./md-files/saplReference

      - name: Create Subfolder
        run: |
          #ls -hal
          if [ ! -d "docs/3.0.0-SNAPSHOT-MD/saplReference" ]; then
          mkdir -p docs/3.0.0-SNAPSHOT-MD/saplReference
          else
          rm -r docs/3.0.0-SNAPSHOT-MD/saplReference/*
          git commit -m "Update generated SAPL-Reference pages"
          fi

      - name: Copy Generated SAPL-Reference Pages to Subfolder
        run: |
          #ls -hal
          cp -R md-files/saplReference/_site/* docs/3.0.0-SNAPSHOT-MD/saplReference/
  
      - name: Commit and Push Changes
        run: |
          #ls -hal
          git config --global user.email "ha247@t-online.de"
          git config --global user.name "HAAL2023"
          git add docs/3.0.0-SNAPSHOT-MD/saplReference/
          git commit -m "Update generated SAPL-Reference pages"
          git push --force

#
  build_sapl_website:
    name: Build SAPL-Website
    needs: [changes, build_sapl_reference]
    if: ${{ needs.changes.outputs.rootfolder == 'true' || needs.changes.outputs.subfolder == 'true' }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.1' # Not needed with a .ruby-version file
          bundler-cache: true # runs 'bundle install' and caches installed gems automatically
          cache-version: 0 # Increment this number if you need to re-download cached gems
      - name: Create symlink
        run: |
          latest_doc=$(ls -1d docs/*/ | sort | tail -n 1)
          ln -s $(basename $latest_doc) docs/latest
      - name: Setup Pages
        id: pages
        uses: actions/configure-pages@v4
      - run: bundle exec jekyll build --baseurl "/" # defaults output to '/_site'
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v2.0.0 # This will automatically upload an artifact from the '/_site' directory

  # Deployment job
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build_sapl_website
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v3
